
from typing import Optional


def generate(
    base: str,
    timeframe: str,
    price: Optional[float],
    change_24h: float,
    signal: dict,
) -> str:
    """
    Generate analyst-style HTML commentary for a single asset.

    Parameters
    ----------
    base       : ticker without USDT (e.g. "BTC")
    timeframe  : e.g. "4h"
    price      : current close price
    change_24h : 24h price change percentage
    signal     : output of analytics.compute_signal()

    Returns
    -------
    HTML string — rendered directly in the frontend insight panel.
    """
    sig   = signal.get("signal", "HOLD")
    s20   = signal.get("sma20")
    s50   = signal.get("sma50")

    posture      = _posture(sig)
    trend_text   = _trend_text(sig, price, s20, s50, base, timeframe)
    action_text  = _action_text(sig)
    risk_text    = _risk_text(change_24h)

    paragraphs = [
        f"<p><strong>Technical posture for {base}/USDT</strong> on the {timeframe} timeframe "
        f"is <span class='{posture['cls']}'>{posture['label']}</span>. {posture['context']}</p>",

        f"<p><strong>Trend structure:</strong> {trend_text}</p>",

        f"<p><strong>Decision-support read:</strong> {action_text} "
        f"<em>This is decision support, not financial advice.</em></p>",

        f"<p><strong>Volatility context:</strong> {risk_text}</p>",

        "<p class='small-text'><em>Generated by rule-based NLG · "
        "LLM-swappable without changing frontend or API surface.</em></p>",
    ]
    return "".join(paragraphs)


def generate_market_breadth(results: list[dict]) -> str:
    """Generate market-breadth commentary from scanner results."""
    if not results:
        return "<p class='small-text'>Run a scan to generate market commentary.</p>"

    counts = {"BUY": 0, "SELL": 0, "HOLD": 0}
    for r in results:
        counts[r.get("signal", {}).get("signal", "HOLD")] += 1

    total    = len(results)
    breadth  = counts["BUY"] / max(counts["SELL"], 1)

    if breadth >= 2:
        regime, cls, context = (
            "broadly constructive", "pos",
            "A strong majority of markets show uptrend alignment — broad-based momentum rather than isolated moves."
        )
    elif breadth >= 1:
        regime, cls, context = (
            "cautiously constructive", "pos",
            "More markets trend up than down, but conviction is not yet decisive."
        )
    elif breadth < 0.5:
        regime, cls, context = (
            "broadly defensive", "neg",
            "A majority of markets show downtrend alignment — consistent with sustained risk-off conditions."
        )
    else:
        regime, cls, context = (
            "mixed / range-bound", "neutral",
            "No dominant directional bias. Patience and selectivity typically outperform directional bets here."
        )

    bull_pct = round(counts["BUY"]  / total * 100)
    bear_pct = round(counts["SELL"] / total * 100)
    leaders  = [r["base"] for r in results if r.get("signal", {}).get("signal") == "BUY"][:4]
    laggards = [r["base"] for r in results if r.get("signal", {}).get("signal") == "SELL"][:4]

    parts = [
        f"<p><strong>Market regime:</strong> Across {total} markets scanned, breadth reads "
        f"<span class='{cls}'>{regime}</span>. {context}</p>",

        f"<p><strong>Signal distribution:</strong> "
        f"{counts['BUY']} BUY ({bull_pct}%) · {counts['HOLD']} HOLD · {counts['SELL']} SELL ({bear_pct}%).</p>",
    ]
    if leaders:
        parts.append(f"<p><strong>Trend leaders:</strong> <span class='pos'>{', '.join(leaders)}</span> "
                     f"show Price &gt; SMA20 &gt; SMA50 alignment.</p>")
    if laggards:
        parts.append(f"<p><strong>Trend laggards:</strong> <span class='neg'>{', '.join(laggards)}</span> "
                     f"show Price &lt; SMA20 &lt; SMA50 alignment.</p>")

    parts.append("<p class='small-text'><em>Rule-based NLG · LLM-swappable</em></p>")
    return "".join(parts)


# ── Internal helpers ──────────────────────────────────────────────────────────

_POSTURE_MAP = {
    "BUY": {
        "label": "constructively biased", "cls": "pos",
        "context": "Price is trading above both moving averages in the correct order, "
                   "confirming uptrend alignment across short and medium-term timeframes.",
    },
    "SELL": {
        "label": "defensively positioned", "cls": "neg",
        "context": "Price is trading below both moving averages in the correct order, "
                   "confirming downtrend alignment across short and medium-term timeframes.",
    },
    "HOLD": {
        "label": "neutral / transitional", "cls": "neutral",
        "context": "Moving averages are not in clear alignment. "
                   "The market is likely consolidating or in an early trend transition.",
    },
}


def _posture(sig: str) -> dict:
    return _POSTURE_MAP.get(sig, _POSTURE_MAP["HOLD"])


def _trend_text(sig: str, price, s20, s50, base: str, timeframe: str) -> str:
    if s20 is None or s50 is None:
        return "Insufficient data to assess trend structure."
    if sig == "BUY":
        return (
            f"<strong>{base}</strong> is currently trading above both the 20-period and "
            f"50-period moving averages (SMA20: <code>{_fmt(s20)}</code>, "
            f"SMA50: <code>{_fmt(s50)}</code>), indicating constructive trend alignment "
            f"and bullish momentum on the {timeframe} timeframe. "
            f"Pullbacks toward SMA20 have historically offered re-entry zones in similar setups."
        )
    if sig == "SELL":
        return (
            f"<strong>{base}</strong> is trading below both the 20-period and "
            f"50-period moving averages (SMA20: <code>{_fmt(s20)}</code>, "
            f"SMA50: <code>{_fmt(s50)}</code>), indicating established downtrend alignment "
            f"on the {timeframe} timeframe. "
            f"Rallies toward SMA20 have historically served as distribution zones rather than reversals."
        )
    return (
        f"Price is near the moving averages (SMA20: <code>{_fmt(s20)}</code>, "
        f"SMA50: <code>{_fmt(s50)}</code>), suggesting consolidation or an early "
        f"trend transition — not yet a clear directional setup."
    )


def _action_text(sig: str) -> str:
    if sig == "BUY":
        return ("Conditions favor <strong>watchlist activation</strong>. "
                "Uptrend alignment supports considering entries with defined risk.")
    if sig == "SELL":
        return ("Conditions support <strong>defensive posture</strong>. "
                "Downtrend alignment argues against new long exposure.")
    return ("Conditions favor <strong>patience</strong>. "
            "No clear directional edge — waiting for trend alignment to develop is rational.")


def _risk_text(change_24h: float) -> str:
    abs_chg = abs(change_24h)
    pct = f"{'+'if change_24h >= 0 else ''}{change_24h:.2f}%"
    if abs_chg > 8:
        return (f"24h move of <strong>{pct}</strong> indicates "
                f"<span class='neg'>elevated short-term volatility</span>. Size conservatively.")
    if abs_chg > 4:
        return (f"24h move of <strong>{pct}</strong> reflects "
                f"<span class='neutral'>moderate volatility</span> — account for noise in stop placement.")
    return (f"24h move of <strong>{pct}</strong> indicates "
            f"<span class='pos'>subdued volatility</span>. Directional moves can emerge quickly from low-vol bases.")


def _fmt(v) -> str:
    if v is None:
        return "—"
    if v >= 1000:
        return f"${v:,.2f}"
    if v >= 1:
        return f"${v:.4f}"
    return f"${v:.6f}"
